name: myworkflow # workflow name
on: [push, workflow_dispatch] #event - trigger

jobs:
  first-job:
    runs-on: ubuntu-latest #runner
    steps:
      - name: print welcome
        run: echo "Hello, world"

      - name: print Goodbye
        run: |
          echo "byebye",
          echo "section1"